[package]
name = "worker"
version = "0.1.0"
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# workspace
tokio.workspace = true
alloy-primitives = { workspace = true, features = [
	"getrandom",
] } #alloy-primitives.workspace = true
reqwest.workspace = true


# local
op-succinct-host-utils.workspace = true
network-lib = { path = "../network-lib" }

# sp1
sp1-sdk.workspace = true

anyhow.workspace = true
dotenv.workspace = true
op-succinct-client-utils.workspace = true
serde.workspace = true
serde_json.workspace = true
csv.workspace = true
# server
axum = "0.7.4"
bincode.workspace = true
log.workspace = true
base64.workspace = true
tower-http.workspace = true
serde_repr = "0.1.19"

[build-dependencies]
op-succinct-build-utils.workspace = true
